#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
 #define REVISION_DB_REALMD "required_s2421_01_realmd_account_locale_agnostic"
 #define REVISION_DB_CHARACTERS "required_s2423_01_characters_item_instance_duration_default"
 #define REVISION_DB_MANGOS "required_s2425_01_mangos_creature_spawn_tideup"
#endif // __REVISION_SQL_H__
