CREATE TABLE `autobroadcast` (
	`id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`ratio` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
