ALTER TABLE db_version CHANGE COLUMN required_s2342_01_mangos_game_event_creature_data required_s2343_01_mangos_quest_template bit;

ALTER TABLE quest_template
ADD COLUMN RewMaxRepValue1 MEDIUMINT(8) NOT NULL DEFAULT 0 AFTER RewRepValue5,
ADD COLUMN RewMaxRepValue2 MEDIUMINT(8) NOT NULL DEFAULT 0 AFTER RewMaxRepValue1,
ADD COLUMN RewMaxRepValue3 MEDIUMINT(8) NOT NULL DEFAULT 0 AFTER RewMaxRepValue2,
ADD COLUMN RewMaxRepValue4 MEDIUMINT(8) NOT NULL DEFAULT 0 AFTER RewMaxRepValue3,
ADD COLUMN RewMaxRepValue5 MEDIUMINT(8) NOT NULL DEFAULT 0 AFTER RewMaxRepValue4;
